#!/usr/bin/env bash
# Bash script to display information about subdomains

print_info () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_info "$2.$1" "$2"
else
    domains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${domains[@]}"
    do
        print_info "$subdomain.$1" "$subdomain"
    done
fi
