#!/usr/bin/env bash
# Domain configuration

process ()
{
  domain="$1"
  subdomain="$2"
  
  dig "$subdomain"."$domain" | tail -n 7 | head -n 1 | awk -v subdomain="${subdomain}" '{print "The subdomain " subdomain " is a " $4 " record and points to " $5}'
}

if [ -z "$2" ]
then
  for subdomain in 'www' 'lb-01' 'web-01' 'web-02'
  do
    process "$1" "$subdomain"
  done
else
  process "$1" "$2"
fi

