#!/usr/bin/env bash
# Script that configures a brand new Ubuntu machine to add a custom HTTP response header to Nginx
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By \"\$HOSTNAME\";/" /etc/nginx/sites-available/default
service nginx start
