#!/usr/bin/env bash
#installing haproxy and configure on lb-01 server
# Install HAProxy
sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http-in
        bind *:80
        default_backend servers
backend servers
        balance roundrobin
        server web-01 100.25.198.206:80 check
        server web-02 52.91.135.184:80 check
EOT

# start HAProxy
sudo /etc/init.d/haproxy start

# set HAProxy to start on boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
